apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluentd.conf: |
    <match fluent.**>
      @type null
    </match>

    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head false
      <parse>
        @type json
        json_parser oj
        time_format %Y-%m-%dT%H:%M:%S
      </parse>
    </source>

    <filter kubernetes.var.log.containers.**>
      @type parser
      <parse>
        @type json
        json_parser oj
        time_format %Y-%m-%dT%H:%M:%S
      </parse>
      key_name log
      replace_invalid_sequence true
      emit_invalid_record_to_error true
      reserve_data true
    </filter>

    <match kubernetes.**>
      @type kafka2
       brokers <broker ip>
      use_event_time true
      topic_key test
      default_topic test
      <buffer>
        @type file
        path /var/log/td-agent/buffer/td
        flush_thread_count 8
        flush_interval 1s
        chunk_limit_size 16M
        queue_limit_length 32
        retry_max_interval 30
        # retry_forever true
      </buffer>
        <format>
        @type json
        </format>
        required_acks -1
        compression_codec gzip
    </match>